import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import EmptyPage from './components/404';
import { useEffect } from 'react';
import LoggerFactory from '../lib/Log';
const Logger = LoggerFactory.initNS('HomePage');
import BrowserLogger from 'alife-logger';

const Home: NextPage = () => {
    useEffect(() => {
        import('alife-logger').then((res) => {
            const BrowserLogger = res.default;
            BrowserLogger.singleton(
                {
                    pid: 'dzt5gjlqog@cfd8f431d4ba146',
                    appType: 'web',
                    imgUrl: 'https://arms-retcode.aliyuncs.com/r.png?',
                    sendResource: true,
                    enableLinkTrace: true,
                    behavior: true,
                    enableSPA: true,
                    useFmp: true,
                    enableConsole: false
                }
            );
        });
        Logger.info('load HomePage');
    }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>甘小虎的个人网站</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <EmptyPage />
      </main>

      <footer className={styles.footer}>
        <div className={styles.copyright}>
          <a className={styles.link}
           target="_blank"
           rel="noreferrer"
           href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33011002016295">
             <Image src="/copyright.png" alt="" width={20} height={20} />
             <p>浙公网安备 33011002016295号</p>
             </a>
        </div>
      </footer>
    </div>
  )
}


export default Home
